CREATE TABLE IF NOT EXISTS `category` (
  `seq` INT(11) NOT NULL AUTO_INCREMENT,
  `categoryName` VARCHAR(20) NOT NULL,
  `description` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`seq`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS `delivery` (
  `seq` INT(11) NOT NULL AUTO_INCREMENT,
  `sessionId` VARCHAR(50) NULL DEFAULT NULL,
  `name` VARCHAR(20) NULL DEFAULT NULL,
  `deliveryDate` VARCHAR(20) NULL DEFAULT NULL,
  `nation` VARCHAR(20) NULL DEFAULT NULL,
  `zipCode` VARCHAR(10) NULL DEFAULT NULL,
  `address` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`seq`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `member` (
  `id` VARCHAR(10) NOT NULL,
  `password` VARCHAR(10) NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  `gender` VARCHAR(4) NULL DEFAULT NULL,
  `birth` VARCHAR(10) NULL DEFAULT NULL,
  `mail` VARCHAR(30) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `postcode` VARCHAR(5) NULL DEFAULT NULL,
  `address` VARCHAR(200) NULL DEFAULT NULL,
  `detailAddress` VARCHAR(100) NULL DEFAULT NULL,
  `extraAddress` VARCHAR(50) NULL DEFAULT NULL,
  `regist_day` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `product` (
  `p_id` VARCHAR(10) NOT NULL,
  `p_name` VARCHAR(20) NULL DEFAULT NULL,
  `p_unitPrice` INT(11) NULL DEFAULT NULL,
  `p_description` TEXT NULL DEFAULT NULL,
  `p_category` VARCHAR(20) NULL DEFAULT NULL,
  `p_manufacturer` VARCHAR(20) NULL DEFAULT NULL,
  `p_unitsinstock` MEDIUMTEXT NULL DEFAULT NULL,
  `p_condition` VARCHAR(20) NULL DEFAULT NULL,
  `p_fileName` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`p_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `sale` (
  `seq` INT(11) NOT NULL AUTO_INCREMENT,
  `saleDate` VARCHAR(20) NULL DEFAULT NULL,
  `sessionId` VARCHAR(50) NULL DEFAULT NULL,
  `productId` VARCHAR(20) NULL DEFAULT NULL,
  `unitPrice` INT(11) NULL DEFAULT NULL,
  `saleQty` INT(11) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`seq`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `status` (
  `statusNumber` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`statusNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

select*from product